<?php
/**
 * SaveTransactionsResponseData
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  RickPelletier\YnabSDKPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RickPelletier\YnabSDKPHP\Model;

use \ArrayAccess;
use \RickPelletier\YnabSDKPHP\ObjectSerializer;

/**
 * SaveTransactionsResponseData Class Doc Comment
 *
 * @category Class
 * @package  RickPelletier\YnabSDKPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SaveTransactionsResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SaveTransactionsResponse_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'transaction_ids' => 'string[]',
        'transaction' => '\RickPelletier\YnabSDKPHP\Model\TransactionDetail',
        'transactions' => '\RickPelletier\YnabSDKPHP\Model\TransactionDetail[]',
        'duplicate_import_ids' => 'string[]',
        'server_knowledge' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'transaction_ids' => null,
        'transaction' => null,
        'transactions' => null,
        'duplicate_import_ids' => null,
        'server_knowledge' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_ids' => 'transaction_ids',
        'transaction' => 'transaction',
        'transactions' => 'transactions',
        'duplicate_import_ids' => 'duplicate_import_ids',
        'server_knowledge' => 'server_knowledge'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transaction_ids' => 'setTransactionIds',
        'transaction' => 'setTransaction',
        'transactions' => 'setTransactions',
        'duplicate_import_ids' => 'setDuplicateImportIds',
        'server_knowledge' => 'setServerKnowledge'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transaction_ids' => 'getTransactionIds',
        'transaction' => 'getTransaction',
        'transactions' => 'getTransactions',
        'duplicate_import_ids' => 'getDuplicateImportIds',
        'server_knowledge' => 'getServerKnowledge'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transaction_ids'] = $data['transaction_ids'] ?? null;
        $this->container['transaction'] = $data['transaction'] ?? null;
        $this->container['transactions'] = $data['transactions'] ?? null;
        $this->container['duplicate_import_ids'] = $data['duplicate_import_ids'] ?? null;
        $this->container['server_knowledge'] = $data['server_knowledge'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['transaction_ids'] === null) {
            $invalidProperties[] = "'transaction_ids' can't be null";
        }
        if ($this->container['server_knowledge'] === null) {
            $invalidProperties[] = "'server_knowledge' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transaction_ids
     *
     * @return string[]
     */
    public function getTransactionIds()
    {
        return $this->container['transaction_ids'];
    }

    /**
     * Sets transaction_ids
     *
     * @param string[] $transaction_ids The transaction ids that were saved
     *
     * @return self
     */
    public function setTransactionIds($transaction_ids)
    {
        $this->container['transaction_ids'] = $transaction_ids;

        return $this;
    }

    /**
     * Gets transaction
     *
     * @return \RickPelletier\YnabSDKPHP\Model\TransactionDetail|null
     */
    public function getTransaction()
    {
        return $this->container['transaction'];
    }

    /**
     * Sets transaction
     *
     * @param \RickPelletier\YnabSDKPHP\Model\TransactionDetail|null $transaction transaction
     *
     * @return self
     */
    public function setTransaction($transaction)
    {
        $this->container['transaction'] = $transaction;

        return $this;
    }

    /**
     * Gets transactions
     *
     * @return \RickPelletier\YnabSDKPHP\Model\TransactionDetail[]|null
     */
    public function getTransactions()
    {
        return $this->container['transactions'];
    }

    /**
     * Sets transactions
     *
     * @param \RickPelletier\YnabSDKPHP\Model\TransactionDetail[]|null $transactions If multiple transactions were specified, the transactions that were saved
     *
     * @return self
     */
    public function setTransactions($transactions)
    {
        $this->container['transactions'] = $transactions;

        return $this;
    }

    /**
     * Gets duplicate_import_ids
     *
     * @return string[]|null
     */
    public function getDuplicateImportIds()
    {
        return $this->container['duplicate_import_ids'];
    }

    /**
     * Sets duplicate_import_ids
     *
     * @param string[]|null $duplicate_import_ids If multiple transactions were specified, a list of import_ids that were not created because of an existing `import_id` found on the same account
     *
     * @return self
     */
    public function setDuplicateImportIds($duplicate_import_ids)
    {
        $this->container['duplicate_import_ids'] = $duplicate_import_ids;

        return $this;
    }

    /**
     * Gets server_knowledge
     *
     * @return int
     */
    public function getServerKnowledge()
    {
        return $this->container['server_knowledge'];
    }

    /**
     * Sets server_knowledge
     *
     * @param int $server_knowledge The knowledge of the server
     *
     * @return self
     */
    public function setServerKnowledge($server_knowledge)
    {
        $this->container['server_knowledge'] = $server_knowledge;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


