<?php
/**
 * ScheduledTransactionDetailAllOfTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  RickPelletier\YnabSDKPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace RickPelletier\YnabSDKPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ScheduledTransactionDetailAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description ScheduledTransactionDetailAllOf
 * @package     RickPelletier\YnabSDKPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScheduledTransactionDetailAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScheduledTransactionDetailAllOf"
     */
    public function testScheduledTransactionDetailAllOf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payee_name"
     */
    public function testPropertyPayeeName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "category_name"
     */
    public function testPropertyCategoryName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subtransactions"
     */
    public function testPropertySubtransactions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
